"""Add address fields to Address and Restaurant models

Revision ID: a06942333c30
Revises: bdc33cf07627
Create Date: 2026-04-22 11:43:44.368143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06942333c30'
down_revision = 'bdc33cf07627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landmark', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(length=20), nullable=True))

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landmark', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('pincode')
        batch_op.drop_column('city')
        batch_op.drop_column('landmark')
        batch_op.drop_column('address_line')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('pincode')
        batch_op.drop_column('city')
        batch_op.drop_column('landmark')

    # ### end Alembic commands ###
