"""Enhance models with location, cutoff times, and availability

Revision ID: bdc33cf07627
Revises: 
Create Date: 2026-04-22 10:43:32.052896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc33cf07627'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quantity_available', sa.Integer(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_type', sa.Enum('Dine-In', 'Takeaway', 'Delivery'), nullable=True))
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'addresses', ['address_id'], ['id'])

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
        batch_op.add_column(sa.Column('delivery_cutoff', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('dine_in_takeaway_cutoff', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('max_delivery_distance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('max_delivery_distance')
        batch_op.drop_column('dine_in_takeaway_cutoff')
        batch_op.drop_column('delivery_cutoff')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('address_id')
        batch_op.drop_column('order_type')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('quantity_available')
        batch_op.drop_column('is_available')

    op.drop_table('addresses')
    # ### end Alembic commands ###
